#+DATE: April 30, 2022
#+AUTHOR: Wanderson Ferreira

Doom Emacs + Evil mode.

I'm enjoying a lot.

After 10 years of standard Emacs keybindings this was a big jump.

Enjoy and be patient if traveling the same waters.

[[file:docs/README.org][Learn more about Doom and Evil]]

[[file:docs/try-this-out.org][Do you want to try this out?]]

* To consider ...

When I setup a new machine from scratch, which does not happen very often, I
have no idea what to install, or what are the very essential tools I will need.

I don't like the idea of using a ~Brewfile~ to install everything I had before,
because seems to me that a fresh start should not start with tons of apps that I
needed in the past for a specific reason that I don't recall anymore.

However, Emacs is always essential. This repo is the first thing I clone and
make sure that is working.

I am considering adding a new folder for *essentials for fresh machine* that will
be triggered from here. Let's see! When the next restart happen, I might work on that.

* FAQ

Let me help myself for the future again!

** Have no idea how to setup Doom Emacs again! I know

#+begin_src bash
## clone this repo in the ~/.doom.d folder
git clone --recurse-submodules git@github.com:wandersoncferreira/evil.git ~/.doom.d

## install doom emacs (got this from their repo)
git clone --depth 1 https://github.com/doomemacs/doomemacs ~/.config/emacs
~/.config/emacs/bin/doom install
#+end_src

** Forgot to include the submodules after a clone, right?

#+begin_src bash
git submodule update --init --recursive
#+end_src

** Need to update  all submodules with remote, you lazy?

#+begin_src bash
git pull --recurse-submodules --jobs=10
#+end_src

** Before figuring out that Doom Emacs doesn't start, pay attention to these deps

*** Python deps

Using macOS?

#+begin_src bash
## create a BASE python3 environment
python3 -m venv base
source base/bin/activate

## install dependencies
python3 -m pip install isort nose pipenv pytest

## when working with python, activate the env with pyvenv emacs package
## M-x pyvenv-activate RET base
#+end_src

*** System  deps

#+begin_src bash
## plantuml
brew install plantuml

## ripgrep
brew install rg
#+end_src

** Emacs is using your $HOME folder as root project

You probably have ~package.json~ in the ~$HOME~ dir. I was caught by this mistake 3
times already.

Anyway, one the ~projectile-project-root-files~ is in your ~$HOME~, just remove it,
it is probably there because you did something wrong!
